"""Add sent column to articles

Revision ID: 0e007ec1020b
Revises: 1c8913b5f88b
Create Date: 2021-05-07 17:10:23.248042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e007ec1020b'
down_revision = '1c8913b5f88b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('sent', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'sent')
    # ### end Alembic commands ###
