"""Change to last article date

Revision ID: 2c327d3320ce
Revises: 2fc67e7c9aed
Create Date: 2021-09-21 16:08:52.277680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c327d3320ce'
down_revision = '2fc67e7c9aed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agency', sa.Column('last_date', sa.Date(), nullable=True))
    op.drop_constraint('agency_last_article_id_fkey', 'agency', type_='foreignkey')
    op.drop_column('agency', 'last_article_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agency', sa.Column('last_article_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('agency_last_article_id_fkey', 'agency', 'article', ['last_article_id'], ['id'])
    op.drop_column('agency', 'last_date')
    # ### end Alembic commands ###
