"""Add last_article

Revision ID: 2fc67e7c9aed
Revises: 0e007ec1020b
Create Date: 2021-09-21 15:08:10.819951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fc67e7c9aed'
down_revision = '0e007ec1020b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agency', sa.Column('last_article_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'agency', 'article', ['last_article_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agency', type_='foreignkey')
    op.drop_column('agency', 'last_article_id')
    # ### end Alembic commands ###
