"""add data and indexes

Revision ID: db40b500c6b8
Revises: 2c327d3320ce
Create Date: 2021-10-01 20:24:29.426828

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'db40b500c6b8'
down_revision = '2c327d3320ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agency', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('article', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_article_agency_id'), 'article', ['agency_id'], unique=False)
    op.create_index(op.f('ix_article_date'), 'article', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_article_date'), table_name='article')
    op.drop_index(op.f('ix_article_agency_id'), table_name='article')
    op.drop_column('article', 'data')
    op.drop_column('agency', 'data')
    # ### end Alembic commands ###
