"""Initial migration

Revision ID: 25d0c0af9b71
Revises: 
Create Date: 2021-05-04 09:30:05.806869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25d0c0af9b71'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('homepage', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('byline', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('pos', sa.Float(), nullable=True),
    sa.Column('neu', sa.Float(), nullable=True),
    sa.Column('neg', sa.Float(), nullable=True),
    sa.Column('compound', sa.Float(), nullable=True),
    sa.Column('agency_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agency.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    op.drop_table('agency')
    # ### end Alembic commands ###
